# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Haoyu Huang
# Description of the Site
description: 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/title.jpg
# Keywords of the Site
site-keywords: 
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://user-images.githubusercontent.com/26505854/205852305-7495b149-b1e3-4fd7-94c6-ccd1abe87a90.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: louishhy5557@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: louishhy
github_username:  louishhy
steam_username: 76561198189168023
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Haoyu Huang
# URL for the Image of the Author
author-image: assets/images/author.jpg
# 60 Words About the Author
author-about: Hi!👋 I am Haoyu Huang (黄皓煜) from Department of Computer Science, The University of Hong Kong. I am currently a research assistant at <a class="no-margin" href="https://aiot.hku.hk/">HKU AIoT lab</a>, focusing on the topic of Computer Vision based HCI.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/louishhy

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
